FloridoERPTX/Controllers/CreditNotes/CreditNotesController.cs
using App.BLL.CreditNotes;
using App.BLL.Invoices;
using App.BLL.Lookups;
using App.BLL.Ma_Tax;
using App.BLL.Sales;
using App.Entities.ViewModels.Common;
using App.Entities.ViewModels.CreditNotes;
using App.Entities.ViewModels.Invoices;
using System.Web.Mvc;
using FloridoERPTX.Reports;
using DevExpress.XtraReports.UI;
using System;
using FloridoERPTX.CommonMethods;
using App.Entities;
using FloridoERPTX.Timbrado;
using App.BLL.SysLog;
using App.BLL.Site;
using System.Globalization;
using static App.Entities.ViewModels.Common.Constants;
using App.BLL.TransactionsCustomers;
using Ionic.Zip;
using System.Text;
using System.IO;
using System.Linq;
using System.Xml;
using App.BLL;
using App.BLL.DigitalTaxStamp;

namespace FloridoERPTX.Controllers.CreditNotes
{
    public class CreditNotesController : Controller
    {
        private SalesBusiness _SaleBusiness;
        private InvoiceBusiness _InvoiceBusiness;
        private ReferenceNumberBusiness _ReferenceNumberBusiness;
        private CreditNotesBusiness _CreditNotesBusiness;
        private CreditNotesDetailBusiness _CreditNotesDetailBusiness;
        private CreditNotesDetailTaxBusiness _CreditNotesDetailTaxBusiness;
        private MaTaxBusiness _MaTaxBusiness;
        private InvoiceDetailBusiness _InvoiceDetailBusiness;
        private CreditNotesBonBusiness _CreditNotesBonBusiness;
        private SalesDetailBusiness _SalesDetailBusiness;
        private StampDocument _StampDocument;
        private SysLogBusiness _SysLogBusiness;
        private SiteConfigBusiness _SiteConfigBusiness;
        private TransactionsCustomersBusiness _TransactionsCustomersBusiness;
        private CreditNotesSalesBusiness _CreditNotesSalesBusiness;
        private UserMasterBusiness _UserMasterBussines;
        private DigitalTaxStampBusiness _DigitalTaxStampBusiness;

        private string tipo = "";
        private string status = "";
        private string moneda = "";
        private string timbre = "";
        public CreditNotesController()
        {
            _SaleBusiness = new SalesBusiness();
            _InvoiceBusiness = new InvoiceBusiness();
            _ReferenceNumberBusiness = new ReferenceNumberBusiness();
            _CreditNotesBusiness = new CreditNotesBusiness();
            _CreditNotesDetailBusiness = new CreditNotesDetailBusiness();
            _CreditNotesDetailTaxBusiness = new CreditNotesDetailTaxBusiness();
            _MaTaxBusiness = new MaTaxBusiness();
            _InvoiceDetailBusiness = new InvoiceDetailBusiness();
            _CreditNotesBonBusiness = new CreditNotesBonBusiness();
            _SalesDetailBusiness = new SalesDetailBusiness();
            _StampDocument = new StampDocument();
            _SysLogBusiness = new SysLogBusiness();
            _SiteConfigBusiness = new SiteConfigBusiness();
            _TransactionsCustomersBusiness = new TransactionsCustomersBusiness();
            _CreditNotesSalesBusiness = new CreditNotesSalesBusiness();
            _UserMasterBussines = new UserMasterBusiness();
            _DigitalTaxStampBusiness = new DigitalTaxStampBusiness();
        }

        #region Reports
        ///REPORTES
        public ActionResult CRNO003()
        {
            CreditNotesBonIndex Model = new CreditNotesBonIndex();
            Model.StartDate = DateTime.Now.Date.ToString(DateFormat.INT_DATE);
            Model.EndDate = DateTime.Now.Date.ToString(DateFormat.INT_DATE);
            Model.CreditNotesBonList = _CreditNotesBonBusiness.GetCreditNotesBonLis(Model);
            Model.CanEditDate = CanEditDate();
            return View(Model);
        }

        [HttpPost]
        public ActionResult CRNO003(CreditNotesBonIndex model)
        {
            model.CreditNotesBonList = _CreditNotesBonBusiness.GetCreditNotesBonLis(model);
            model.CreditNotesBonList.ForEach(x => x.xml = string.Empty);
            //return Json(new { success = true, Json = model }, JsonRequestBehavior.AllowGet);
            model.CanEditDate = CanEditDate();
            return View(model);
        }
        private void getEstados(CreditNotesBonIndex model)
        {
            if (model.Currency == Currencys.MXN)
            {
                moneda = "Pesos";

            }
            if (model.Currency == Currencys.USD)
            {
                moneda = "Dolares";
            }
            if (model.Status == CreditNoteStatus.All)
            {
                status = "Todas";
            }
            if (model.Status == CreditNoteStatus.Active)
            {
                status = "Ativas";

            }
            if (model.Status == CreditNoteStatus.Cancelled)
            {
                status = "Canceladas";
            }
            if (model.Type == CreditNoteTypesReports.All)
            {
                tipo = "Todas";
            }
            if (model.Type == CreditNoteTypesReports.Bonification)
            {
                tipo = "Bonificación";

            }
            if (model.Type == CreditNoteTypesReports.CreditNote)
            {
                tipo = "Nota de Crédito";
            }
            if (model.Uuid == CreditNoteStatusFiscal.All)
            {
                timbre = "Todas";
            }
            if (model.Uuid == CreditNoteStatusFiscal.SinTimbre)
            {
                timbre = "Sin Timbrar";

            }
            if (model.Uuid == CreditNoteStatusFiscal.Timbrada)
            {
                timbre = "Timbradas";
            }

        }
        
        [HttpPost]
        public ActionResult ActionReportGral(CreditNotesBonIndex model)
        {
            getEstados(model);
            CreditNotesReport report = new CreditNotesReport();
            string siteName = _SiteConfigBusiness.GetSiteCodeName();
            (report.Bands["DetailReport"] as DetailReportBand).DataSource = report.printTable(model.CreditNotesBonList, model.StartDate, model.EndDate, moneda, tipo, status, siteName);
            (report.Bands["DetailReport"] as DetailReportBand).DataMember = "xrTableRowFormat";
            return PartialView("~/Views/ReportsViews/CreditNotesReport.cshtml", report);
        }
       
        public ActionResult ActionGetCreditNotesBonDetail(long cnId, decimal importe)
        {
            return Json(new { success = true, Json = _CreditNotesBonBusiness.GetCreditNotesBondeDetailList(cnId, importe) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionReportCreditNotesDetails(long cnId, string folio, decimal importe, string date, string invoice, string customer, string type)
        {
            SalesReportDetail report = new SalesReportDetail();
            string siteName = _SiteConfigBusiness.GetSiteCodeName();
            (report.Bands["DetailReport"] as DetailReportBand).DataSource = report.printTable(_CreditNotesBonBusiness.GetCreditNotesBondeDetailList(cnId, importe), folio, date, invoice, true, siteName, customer, type);
            (report.Bands["DetailReport"] as DetailReportBand).DataMember = "xrTableRowFormat";
            return PartialView("~/Views/ReportsViews/SaleReportView.cshtml", report);
        }

        public ActionResult ActionGetXMLCreditNotes(CreditNotesBonIndex Model)
        {
            var List = _CreditNotesBonBusiness.GetCreditNotesBonLis(Model);
            using (ZipFile zip = new ZipFile())
            {
                foreach (var item in List.Where(c => !string.IsNullOrEmpty(c.xml)))
                {
                    byte[] xmlFile = null;
                    string fileName = string.Format("{0}.xml", item.CfdNotaNo);
                    xmlFile = Encoding.UTF8.GetBytes(item.xml);
                    zip.AddEntry(fileName, xmlFile);
                }

                if (zip.Count > 0)
                {
                    DateTime StartDate = DateTime.ParseExact(Model.StartDate, DateFormat.INT_DATE, CultureInfo.InvariantCulture);
                    DateTime EndDate = DateTime.ParseExact(Model.EndDate, DateFormat.INT_DATE, CultureInfo.InvariantCulture);
                    string zipName = string.Format("Notas de Crédito/Bonificaciones del {0} al {1}.zip", StartDate.ToString("d", CultureInfo.CreateSpecificCulture("de-DE")), EndDate.ToString("d", CultureInfo.CreateSpecificCulture("de-DE")));
                    using (MemoryStream output = new MemoryStream())
                    {
                        zip.Save(output);
                        return File(output.ToArray(), "application/zip", zipName);
                    }
                }
            }
            return null;
        }

        public ActionResult ActionGetXMLFile(long DocumentNo)
        {
            XmlDocument doc = new XmlDocument();
            var DocumentItem = _CreditNotesBusiness.GetCreditNoteByNumber(DocumentNo);
            string fileName = string.Format("{0}{1}.xml", DocumentItem.cn_serie, DocumentItem.cn_id);

            using (MemoryStream output = new MemoryStream())
            {
                doc.LoadXml(DocumentItem.xml);
                XmlTextWriter writer = new XmlTextWriter(output, Encoding.UTF8);
                doc.WriteTo(writer);
                writer.Flush();
                Response.Clear();
                byte[] byteArray = output.ToArray();
                Response.AppendHeader("Content-Disposition", "filename=" + fileName);
                Response.AppendHeader("Content-Length", byteArray.Length.ToString());
                Response.ContentType = "application/octet-stream";
                Response.BinaryWrite(byteArray);
                writer.Close();
            }
            return null;
        }
        #endregion

        #region Create Credit Notes and Bonifications
        public ActionResult CRNO001()
        {
            CreditNoteIndex Model = new CreditNoteIndex();
            return View(Model);
        }

        [HttpPost]
        public ActionResult CRNO001(CreditNoteIndex Model)
        {
            CreditNote Item = new CreditNote();

FloridoERPTX/Views/CreditNotes/CRNO001.cshtml
@model App.Entities.ViewModels.CreditNotes.CreditNoteIndex

@{
    ViewBag.Title = "Notas de Crédito";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Breadcrumb*@
<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("SALE000","Sales")">Ventas</a></li>
                    <li><a href="@Url.Action("SALE004","Sales")">Movimientos</a></li>
                    <li class="active">
                        <span>Nota de Crédito</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Notas de Crédito
            </h2>
            <small>Módulo para notas de crédito</small><br />
        </div>
    </div>
</div>

<div class="content animated-panel">
    <div class="hpanel hblue">
        <div class="panel-body">
            <form id="formCreditNotes" action="@Url.Action("CRNO001", "CreditNotes")" method="post">
                <div class="form-horizontal">
                    <h4 style="margin-left:-5px;">Notas de Crédito</h4>
                    <div class="form-group col-md-4">
                        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10 input-group m-b">
                            @Html.EnumDropDownListFor(model => model.Type, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group col-md-5" id="ItemsSelect">
                        <label class="control-label">&nbsp;</label><br />
                        <div class="form-group col-lg-7">
                            <div class="i-checks">
                                @Html.CheckBoxFor((model => model.SelectItems), new { @class = "form-control" })
                                @Html.LabelFor(model => model.SelectItems, htmlAttributes: new { @class = "control-label" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div id="CreditNoteBoni">
                            <div class="form-group col-md-3">
                                @Html.LabelFor(model => model.InvoiceNumber, htmlAttributes: new { @class = "control-label" })
                                <div class="col-md-10 input-group m-b">
                                    @Html.EditorFor(model => model.InvoiceNumber, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.InvoiceNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-1">
                                <label>- o -</label>
                            </div>
                            <div class="form-group col-md-3">
                                @Html.LabelFor(model => model.SaleNumber, htmlAttributes: new { @class = "control-label" })
                                <div class="col-md-10 input-group m-b">
                                    @Html.EditorFor(model => model.SaleNumber, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.SaleNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-2">
                                <label class="control-label">&nbsp;</label>
                                <div class="text-right">
                                    <button type="button" class="btn btn-success" id="CreditNote">Continuar</button>
                                </div>
                            </div>
                        </div>
                        <div id="EmployeeBoni">
                            <div class="form-group col-md-3">
                                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label" })
                                <div class="col-md-10 input-group m-b">
                                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-1"></div>
                            <div class="form-group col-md-3"></div>
                            <div class="form-group col-md-2">
                                <label class="control-label">&nbsp;</label>
                                <div class="text-right">
                                    <button type="button" class="btn btn-success" id="EmployeeBoniCreate">Continuar</button>
                                </div>
                            </div>
                            <br /><br />
                            <br /><br />
                            <br /><br />
                            <div class="form-group" id="EmployeeBoniError">
                                <h5 style="color:red; margin-top:-3%;" class="col-md-12 EmployeBoniErrorMsg"></h5>
                            </div>
                        </div>
                    </div>
                    <div class="form-group" id="ErrorMessage">
                        <h5 style="color:red; margin-top:-3%;" class="col-md-12">Introduce el No. de Factura o el No. de Venta</h5>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var errorMessage;
        var saleNumber;
        var invoiceNumber;
        var validValueSale;
        var validValueInvoice;
        $(function () {
            $("#ErrorMessage").hide();
            $("#EmployeeBoni").hide();
            $("#EmployeeBoniError").hide();
            $("#ItemsSelect").hide();

            dateInput = $("#Date").datepicker({
                autoclose: true,
                todayHighlight: true,
                format: 'dd/mm/yyyy',
                language: 'es',
                endDate: new Date()
            });

            $(".datepicker").attr('readonly', 'readonly').css('background-color', '#fff');

            $("#formCreditNotes").validate({
                errorClass: 'help-block animation-slideDown', // You can change the animation class for a different entrance animation - check animations page
                errorElement: "span",
                errorPlacement: function (error, element) {
                    $(element)
                            .closest("form")
                            .find("span[data-valmsg-for='" + element.attr("id") + "']")
                            .append(error);
                },
                highlight: function (e) {
                    $("#CreditNote").attr("disabled", "disabled");
                    $(e).closest('.form-group').removeClass('has-success has-error').addClass('has-error');
                    $(e).closest('.help-block').remove();
                },
                success: function (e) {
                    $("#CreditNote").removeAttr("disabled");
                    e.closest('.form-group').removeClass('has-success has-error');
                    e.closest('.help-block').remove();
                },
                rules: {
                    SaleNumber: {
                        digits: true,
                        required: true,
                        remote: function () {
                            saleNumber = $('#SaleNumber').val();
                            typeSelection = $("#Type").val();
                            var valid = {
                                url: "@(Url.Action("ActionValidateSale", "CreditNotes"))",
                                type: "post",
                                data: { "SaleNumber": saleNumber, "Type": typeSelection },
                                dataFilter: function (data) {
                                    EndLoading();
                                    var obj = JSON.parse(data);
                                    if (!obj.success) {
                                        errorMessage = obj.responseText;
                                        return false;
                                    }
                                    return true;
                                }
                            };
                            return valid;
                        },
                    },
                    InvoiceNumber: {
                        digits: true,
                        required: true,
                        remote: function () {
                            invoiceNumber = $("#InvoiceNumber").val();
                            typeSelection = $("#Type").val();
                            var valid = {
                                url: "@(Url.Action("ActionValidateInvoice", "CreditNotes"))",
                                type: "post",
                                data: { "InvoiceNumber": invoiceNumber, "Type": typeSelection },
                                dataFilter: function (data) {
                                    EndLoading();
                                    var obj = JSON.parse(data);
                                    if (!obj.success) {
                                        errorMessage = obj.responseText;
                                        return false;
                                    }
                                    return true;
                                }
                            };
                            return valid;
                        }
                    }
                },
                messages: {
                    SaleNumber: {
                        remote: function () { return errorMessage },
                    },
                    InvoiceNumber: {
                        remote: function () { return errorMessage },
                    }
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });
        });

        $("#CreditNote").click(function () {
            saleNumber = $("#SaleNumber").val();
            invoiceNumber = $("#InvoiceNumber").val();
            if (saleNumber == "" && invoiceNumber == "") {
                $("#formCreditNotes").validate().element("#SaleNumber");
                $("#formCreditNotes").validate().element("#InvoiceNumber");
                $("#ErrorMessage").show();
            }
            else if (saleNumber == "" && $("#formCreditNotes").validate().element("#InvoiceNumber")) {
                $("#SaleNumber").rules("remove", "required");
                StartLoading();
                $("#formCreditNotes").submit();
            } else if (invoiceNumber == "" && $("#formCreditNotes").validate().element("#SaleNumber")) {
                $("#InvoiceNumber").rules("remove", "required");
                StartLoading();
                $("#formCreditNotes").submit();
            }
        });

        $("#SaleNumber").on('change keypress paste', function (e) {
            $("#InvoiceNumber").val("");
            ValidateInputs(e);
        });

        $("#InvoiceNumber").on('change keypress paste', function (e) {
            $("#SaleNumber").val("");
            ValidateInputs(e);
        });

        $("#Type").on('change', function () {
            var value = $(this).val();            
            if (value != 2) {
                $("#EmployeeBoni").hide();
                $("#CreditNoteBoni").show();

                //Show or hide Checkbox to select items for bonifications
                if (value == 1)
                    $("#ItemsSelect").show();
                else
                    $("#ItemsSelect").hide();
               
                ValidateInputs(value);
                $("#CreditNote").removeAttr("disabled");
            }
            else {
                $("#ItemsSelect").hide();
                $("#EmployeeBoni").show();
                $("#CreditNoteBoni").hide();
                $("#ErrorMessage").hide();
            }
        });

        function ValidateInputs(e) {
            $("#ErrorMessage").hide();
            $('.form-group').removeClass('has-success has-error');
            $('.help-block').remove();
            if (e.which == 13 || e.keyCode == 13)
                $("#CreditNote").click();
        }

        $("#EmployeeBoniCreate").click(function () {
            var date = $("#Date").val();
            $.ajax({
                type: "GET",
                url: "@(Url.Action("ActionValidateDate", "CreditNotes"))",
                dataType: 'json',
                data: { "Date": date },
                success: function (data) {
                    if (data.success)
                        $("#formCreditNotes").submit();
                    else {
                        $("#EmployeeBoniError").show();
                        $(".EmployeBoniErrorMsg").html(data.responseText)
                        $("#EmployeeBoniCreate").attr("disabled", "disabled");
                    }
                }
            });
        });

        $("#Date").on('change', function () {
            $("#EmployeeBoniError").hide();
            $("#EmployeeBoniCreate").removeAttr("disabled");
        });

    </script>
}

FloridoERPTX/Views/CreditNotes/_CRNO003.cshtml
@model App.Entities.ViewModels.CreditNotes.CreditNote

    <div class="modal fade" id="ModalEditCreditNote" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="color-line"></div>
                <div class="modal-header">
                    <h4 id="ModalTitle" class="modal-title">Editar Nota de Credito/Bonificación</h4>
                    <small id="ModalDescription" class="font-bold">Cambio de fecha.</small>
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm("ActionEditDocumentDate", "CreditNotes", FormMethod.Post, new { name = "formEditDate", id = "formEditDate" }))
                    {
                        @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        @Html.HiddenFor(model => model.Number)

                        <div class="row">
                            <div class="form-group col-md-12">
                                <label class="control-label">Serie: </label>
                                @Html.DisplayFor(model => model.Serie, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-12">
                                <label class="control-label">Factura: </label>
                                @Html.DisplayFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-12">
                                <label class="control-label">Total: </label>
                                @Html.DisplayFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-12">
                                <label class="control-label">Fecha Actual: </label>
                                @Html.DisplayFor(model => model.IssuedDate, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-3">
                                <label class="control-label">Nueva Fecha: </label>
                                <div class="col-md-12 input-group m-b">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    @Html.EditorFor(model => model.NewIssuedDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                </div>
                            </div>
                        </div>
                    </div>
                        <div class="form-group col-lg-12">
                            <div class="text-right">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                                <button type="button" class="btn btn-success" data-dismiss="modal" id="EditCreditNote" onclick="SaveChanges()">Guardar</button>
                            </div>
                        </div>
                        <br><br>
                    }
                </div>
            </div>
        </div>
        <div id="ajaxTarget">
            <script type="text/javascript">

                $('#NewIssuedDate').datepicker({
                    minDate: 5,
                    autoclose: true,
                    format: 'dd/mm/yyyy',
                    language: 'es'
                });
                
                $("#NewIssuedDate").on('change', function () {
                    var date = stringToDate($("#NewIssuedDate").val());

                    var currentDate = stringToDate(GetCurrentDate());

                    if (date > currentDate) {
                        toastr.error('La fecha de aplicación no puede ser mayor a la fecha de Hoy.');
                        //$("#GenerateCreditNote").attr("disabled", "disabled");
                        $("#NewIssuedDate").attr('style', 'border-color: red !important');
                        $("#EditCreditNote").prop('disabled', true);
                    }
                    else {
                        $("#NewIssuedDate").attr('style', 'border-color: black !important');
                        $("#EditCreditNote").prop('disabled', false);
                    }
                });

                function GetCurrentDate() {
                    var today = new Date();
                    var dd = today.getDate();
                    var mm = today.getMonth() + 1; //January is 0!
                    var yyyy = today.getFullYear();

                    if (dd < 10) {
                        dd = '0' + dd;
                    }

                    if (mm < 10) {
                        mm = '0' + mm;
                    }

                    today = dd + '/' + mm + '/' + yyyy;

                    return today;
                }

                function stringToDate(dateStr) {
                    var parts = dateStr.split("/")
                    return new Date(parts[2], parts[1] - 1, parts[0])
                }
            </script>
        </div>
    </div>