FloridoERPTX/Controllers/POS/PosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FloridoERPTX.Controllers.POS
{
    public class PosController : Controller
    {
        public ActionResult POS000()
        {
            return View();
        }
        public ActionResult POS001()
        {
            return View();
        }
        public ActionResult POS002()
        {
            return View();
        }

    }
}

FloridoERPTX/Controllers/Sales/SalesController.cs
using App.BLL.Sales;
using System;
using System.Web.Mvc;
using App.Entities.ViewModels.Sales;
using FloridoERPTX.Reports;
using DevExpress.XtraReports.UI;
using App.Entities.ViewModels.Common;
using App.BLL.Site;
using System.Collections.Generic;
using System.Linq;
using App.BLL.Lookups;
using App.BLL;
using App.Entities.ViewModels.SalesPriceChange;
using FloridoERP.Report;
using FloridoERPTX.ViewModels;
using App.Entities;
using CustomerSalesViewModel = App.Entities.ViewModels.Sales.CustomerSalesViewModel;
using App.BLL.MaClass;
using App.BLL.Item;
using static App.Entities.ViewModels.Common.Constants;
using FloridoERPTX.CommonMethods;

namespace FloridoERPTX.Controllers.Sales
{
    public class SalesController : Controller
    {
        private SalesBusiness _SalesBussines;
        private SalesDetailBusiness _SalesDetailBusiness;
        private SiteConfigBusiness _SiteConfigBusiness;
        private PortadaBusiness _PortadaBusiness;
        private PaymentMethodBusiness _PaymentMethodBusiness;
        private UserMasterBusiness _UserMasterBusiness;
        private SalesPaymentMethodBusiness _SalesPaymentMethodBusiness;
        private CurrencyDetailBusiness _CurrencyDetailBusiness;
        private SalesPriceChangeBusiness _SalesPriceChangeBusiness;
        private SalesCancellationBusiness _SalesCancellationBusiness;
        private MaClassBusiness _MaClassBusiness;
        private ItemBusiness _ItemBusiness;
        private CashierLookup _CashierLookup;
        private readonly ItemSalesBusiness _ItemSalesBusiness;

        public SalesController()
        {
            _SalesBussines = new SalesBusiness();
            _SalesDetailBusiness = new SalesDetailBusiness();
            _SiteConfigBusiness = new SiteConfigBusiness();
            _PortadaBusiness = new PortadaBusiness();
            _PaymentMethodBusiness = new PaymentMethodBusiness();
            _UserMasterBusiness = new UserMasterBusiness();
            _SalesPaymentMethodBusiness = new SalesPaymentMethodBusiness();
            _CurrencyDetailBusiness = new CurrencyDetailBusiness();
            _SalesPriceChangeBusiness = new SalesPriceChangeBusiness();
            _SalesCancellationBusiness = new SalesCancellationBusiness();
            _MaClassBusiness = new MaClassBusiness();
            _ItemBusiness = new ItemBusiness();
            _CashierLookup = new CashierLookup();
            _ItemSalesBusiness = new ItemSalesBusiness();
        }

        // GET: Sales/Details/5
        public ActionResult ActionGetSaleById(int SaleId)
        {
            var Sale = _SalesBussines.GetSaleByNumber(SaleId);
            return View();
        }

        public ActionResult SALE005()
        {
            //Return true when Cancel Bonification
            return RedirectToAction("ActionCRNO005", "CreditNotes", new { IsBonification = true });
        }

        public ActionResult SALE006()
        {
            //Return false when Cancel Credit Note
            return RedirectToAction("ActionCRNO005", "CreditNotes", new { IsBonification = false });
        }

        #region Reports

        #region Sales Report
        public ActionResult SALE001()
        {
            var model = new SalesIndex();
            model.StartDate = DateTime.Now.Date.ToString(DateFormat.INT_DATE);
            model.EndDate = DateTime.Now.Date.ToString(DateFormat.INT_DATE);
            FillLookupCajas(_SalesBussines.GetCajas());
            ViewBag.Cashier = _CashierLookup.FillLookupCashiers(CashiersLookup.BySale);
            return View(model);
        }

        [HttpPost]
        public ActionResult SALE001(SalesIndex model)
        {
            FillLookupCajas(_SalesBussines.GetCajas());
            ViewBag.Cashier = _CashierLookup.FillLookupCashiers(CashiersLookup.BySale);
            return View(model);
        }

        [HttpGet]
        public ActionResult ActionGetSales(SalesIndex Model)
        {
            var _salesList = _SalesBussines.GetSalesReport(Model);
            if (_salesList != null)
                return new JsonResult() { Data = new { success = true, Json = _salesList }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
            else
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionGetSalesDetail(long saleId)
        {
            return Json(new { success = true, Json = _SalesDetailBusiness.getSalesDetailBySaleId(saleId) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionGetSalesDetailReport(long saId)
        {
            SalesReportDetail report = new SalesReportDetail();
            var saleD = _SalesBussines.GetSaleBySaleId((long)saId);
            string saDate = saleD[0].sale_date.ToString();
            string saInvoice = saleD[0].sale_factura.ToString();
            string siteName = _SiteConfigBusiness.GetSiteCodeName();
            (report.Bands["DetailReport"] as DetailReportBand).DataSource = report.printTable(_SalesDetailBusiness.getSalesDetailBySaleId(saId), saId.ToString(), saDate.ToString(), saInvoice, false, siteName, saleD[0].customer.ToString(), "");
            (report.Bands["DetailReport"] as DetailReportBand).DataMember = "xrTableRowFormat";
            return PartialView("~/Views/ReportsViews/SaleReportView.cshtml", report);

        }

        [HttpPost]
        public ActionResult ActionGetSalesReport(SalesIndex Model)
        {
            SalesReport report = new SalesReport();
            string siteName = _SiteConfigBusiness.GetSiteCodeName();
            var _salesList = _SalesBussines.GetSalesReport(Model);
            (report.Bands["DetailReport"] as DetailReportBand).DataSource = report.printTable(_salesList, Model.StartDate, Model.EndDate, siteName);
            (report.Bands["DetailReport"] as DetailReportBand).DataMember = "xrTableRowFormat";

            return PartialView("~/Views/ReportsViews/SaleReportList.cshtml", report);
        }
        #endregion

        #region Sales Concentrated Report
        public ActionResult SALE002()
        {
            var model = new SalesConcIndex();
            model.StartDate = DateTime.Now.Date.AddDays(-1).ToString(DateFormat.INT_DATE);
            model.EndDate = DateTime.Now.Date.ToString(DateFormat.INT_DATE);
            model.Sales = _SalesBussines.GetSalesConcretated(model);

            return View(model);

        }

        [HttpPost]
        public ActionResult SALE002(SalesConcIndex model)
        {
            model.Sales = _SalesBussines.GetSalesConcretated(model);
            return View(model);
        }

        [HttpPost]
        public ActionResult ActionReportGral(SalesConcIndex model)
        {
            //getEstados(model);
            SalesConcentrated report = new SalesConcentrated();
            string siteName = _SiteConfigBusiness.GetSiteCodeName();
            (report.Bands["DetailReport"] as DetailReportBand).DataSource = report.printTable(model.Sales, model.StartDate, model.EndDate, siteName);
            (report.Bands["DetailReport"] as DetailReportBand).DataMember = "xrTableRowFormat";

            return PartialView("~/Views/ReportsViews/SalesConcentrated.cshtml", report);
        }
        #endregion

        #region Chingon Report
        //reporte portada
        public ActionResult SALE008()
        {
            var model = new PortadaModel();

            var _date = DateTime.Now.Date.ToString(DateFormat.INT_DATE);
            model = _PortadaBusiness.PopulatePortadaModel(_date);
            return View(model);

        }
        [HttpPost]
        public ActionResult SALE008(PortadaModel model)
        {
            model = _PortadaBusiness.PopulatePortadaModel(model.ReportDate);
            return View(model);
        }

        [HttpPost]
        public ActionResult ActionReportGralPortada(PortadaModel model, decimal[] totalesMXN, decimal[] totalesUSD)
        {
            //SalesConcentrated report = new SalesConcentrated();
            model.TotalesMXN = new decimal[7, 3];
            model.TotalesDLLS = new decimal[7, 3];
            model.TotalesMXN[0, 0] = totalesMXN[0]; model.TotalesMXN[0, 1] = totalesMXN[1]; model.TotalesMXN[0, 2] = totalesMXN[2];
            model.TotalesMXN[1, 0] = totalesMXN[3]; model.TotalesMXN[1, 1] = totalesMXN[4]; model.TotalesMXN[1, 2] = totalesMXN[5];
            model.TotalesMXN[2, 0] = totalesMXN[6]; model.TotalesMXN[2, 1] = totalesMXN[7]; model.TotalesMXN[2, 2] = totalesMXN[8];
            model.TotalesMXN[3, 0] = totalesMXN[9]; model.TotalesMXN[3, 1] = totalesMXN[10]; model.TotalesMXN[3, 2] = totalesMXN[11];
            model.TotalesMXN[4, 0] = totalesMXN[12]; model.TotalesMXN[4, 1] = totalesMXN[13]; model.TotalesMXN[4, 2] = totalesMXN[14];
            model.TotalesMXN[5, 0] = totalesMXN[15]; model.TotalesMXN[5, 1] = totalesMXN[16]; model.TotalesMXN[5, 2] = totalesMXN[17];
            model.TotalesMXN[6, 0] = totalesMXN[18]; model.TotalesMXN[6, 1] = totalesMXN[19]; model.TotalesMXN[6, 2] = totalesMXN[20];

            model.TotalesDLLS[0, 0] = totalesUSD[0]; model.TotalesDLLS[0, 1] = totalesUSD[1]; model.TotalesDLLS[0, 2] = totalesUSD[2];
            model.TotalesDLLS[1, 0] = totalesUSD[3]; model.TotalesDLLS[1, 1] = totalesUSD[4]; model.TotalesDLLS[1, 2] = totalesUSD[5];
            model.TotalesDLLS[2, 0] = totalesUSD[6]; model.TotalesDLLS[2, 1] = totalesUSD[7]; model.TotalesDLLS[2, 2] = totalesUSD[8];
            model.TotalesDLLS[3, 0] = totalesUSD[9]; model.TotalesDLLS[3, 1] = totalesUSD[10]; model.TotalesDLLS[3, 2] = totalesUSD[11];
            model.TotalesDLLS[4, 0] = totalesUSD[12]; model.TotalesDLLS[4, 1] = totalesUSD[13]; model.TotalesDLLS[4, 2] = totalesUSD[14];
            model.TotalesDLLS[5, 0] = totalesUSD[15]; model.TotalesDLLS[5, 1] = totalesUSD[16]; model.TotalesDLLS[5, 2] = totalesUSD[17];

FloridoERPTX/Views/POS/POS000.cshtml
@{
    /**/

    ViewBag.Title = "POS000";
}

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div class="font-light m-b-xs text-center">
                <h2>
                    CAJAS
                </h2>
                <small class="text-primary text-center">Menú Cajas</small>
            </div>
        </div>
    </div>
</div>

<div class="content animate-panel">
    <div class="row">





        <div class="col-md-4">
            @*<div class="hpanel hred">*@
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("POS001", "POS")">
                            <h4 class="m-b-md">Movimientos</h4>
                            <div class="m">
                                <i class="pe-7s-albums fa-5x"></i>
                            </div>
                            <p class="small">
                                Menu de Movimientos
                            </p>
                            <br />
                        </a>

                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("POS002", "POS")">
                            <h4 class="m-b-md">Reportes</h4>
                            <div class="m">rEPORT
                                <i class="fa-file fa fa-5x"></i>
                            </div>
                            <p class="small">
                                Menu de Reportes
                            </p>
                            <br />
                        </a>

                    </div>
                </div>
            </div>
        </div>






    </div>

</div>


@section Scripts {
    <script type="text/javascript">
        jQuery(document).ready(function () {
            $("#divIndex").focus();
            window.setTimeout(function () {
                $("#fa").click();
            }, 5000);
        });

    </script>
}

FloridoERPTX/Views/POS/POS001.cshtml
@{
    /**/

    ViewBag.Title = "POS000";
}

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div class="font-light m-b-xs text-center">
                <h2>
                    CAJAS
                </h2>
                <small class="text-primary text-center">Menú Movimientos</small>
            </div>
        </div>
    </div>
</div>

<div class="content animate-panel">
    <div class="row">





        <div class="col-md-4">
            @*<div class="hpanel hred">*@
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center"> 
                        <a href="@Url.Action("SANC001", "Sanctions")">
                            <h4 class="m-b-md">Sanciones</h4>
                            <div class="m">
                                <i class="pe-7s-albums fa-5x"></i>
                            </div>
                            <p class="small">
                                Agregar Sanciones
                            </p>
                            <br />
                        </a>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center"> 
                        <a href="@Url.Action("PART001", "PartnersAccessCard")">
                            <h4 class="m-b-md">Tarjetas de permiso</h4>
                            <div class="m">
                                <i class="pe-7s-albums fa-5x"></i>
                            </div>
                            <p class="small">
                                Tarjetas de permisos de usuarios
                            </p>
                            <br />
                        </a>

                    </div>
                </div>
            </div>
        </div>
       






    </div>

</div>


@section Scripts {
    <script type="text/javascript">
        jQuery(document).ready(function () {
            $("#divIndex").focus();
            window.setTimeout(function () {
                $("#fa").click();
            }, 5000);
        });

    </script>
}

FloridoERPTX/Views/POS/POS002.cshtml
@{
    /**/

    ViewBag.Title = "POS000";
}

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div class="font-light m-b-xs text-center">
                <h2>
                    CAJAS
                </h2>
                <small class="text-primary text-center">Menú Reportes</small>
            </div>
        </div>
    </div>
</div>

<div class="content animate-panel">
    <div class="row">        
        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("SALE012", "Sales")">
                            <h4 class="m-b-md">Cancelaciones por Cajero</h4>
                            <div class="m">
                                <i class="pe-7s-note2 fa-5x"></i>
                            </div>
                            <p class="small">Cancelaciones por Cajero</p>
                            <br />
                        </a>
                        <a href="@Url.Action("SALE012", "Sales")" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>       
        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("WIDR001", "Withdrawal")">
                            <h4 class="m-b-md">Retiros de Caja</h4>
                            <div class="m">
                                <i class="pe-7s-note2 fa-5x"></i>
                            </div>
                            <p class="small">Reporte de Caja</p>
                            <br />
                        </a>
                        <a href="@Url.Action("WIDR001", "Withdrawal")" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>       
        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("SALE009", "Sales")">
                            <h4 class="m-b-md">Ventas por tipo de pago</h4>
                            <div class="m">
                                <i class="pe-7s-note2 fa-5x"></i>
                            </div>
                            <p class="small">Ventas por tipo de pago</p>
                            <br />
                        </a>
                        <a href="@Url.Action("SALE009", "Sales")" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>       
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("SALE010", "Sales")">
                            <h4 class="m-b-md">Cambio de Precios</h4>
                            <div class="m">
                                <i class="pe-7s-note2 fa-5x"></i>
                            </div>
                            <p class="small">Cambio de Precios</p>
                            <br />
                        </a>
                        <a href="@Url.Action("SALE010", "Sales")" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>      
        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("SALE011", "Sales")">
                            <h4 class="m-b-md">Cancelaciones (PV)</h4>
                            <div class="m">
                                <i class="pe-7s-note2 fa-5x"></i>
                            </div>
                            <p class="small">Reporte de Sanciones</p>
                            <br />
                        </a>
                        <a href="@Url.Action("SALE011", "Sales")" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>          
        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("CHOU001", "Checkout")">
                            <h4 class="m-b-md">Corte Z</h4>
                            <div class="m">
                                <i class="pe-7s-note2 fa-5x"></i>
                            </div>
                            <p class="small">Corte Z</p>
                            <br />
                        </a>
                        <a href="@Url.Action("CHOU001", "Checkout")" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("DONA001", "Donations")">
                            <h4 class="m-b-md">Donaciones</h4>
                            <div class="m">
                                <i class="pe-7s-note2 fa-5x"></i>
                            </div>
                            <p class="small">Donaciones</p>
                            <br />
                        </a>
                        <a href="@Url.Action("DONA001", "Donations")" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("DONA002", "Donations")">
                            <h4 class="m-b-md">Donaciones (Boletos)</h4>
                            <div class="m">
                                <i class="pe-7s-note2 fa-5x"></i>
                            </div>
                            <p class="small">Donaciones (Boletos)</p>
                            <br />
                        </a>
                        <a href="@Url.Action("DONA002", "Donations")" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="@Url.Action("SANC002", "Sanctions")">
                            <h4 class="m-b-md">Relación de Sanciones</h4>
                            <div class="m"><i class="pe-7s-note2 fa-5x"></i>
                            </div>
                            <p class="small">Reporte de Sanciones</p>
                            <br />
                        </a>
                        <a href="@Url.Action("SANC002", "Sanctions")" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript">
        jQuery(document).ready(function () {
            $("#divIndex").focus();
            window.setTimeout(function () {
                $("#fa").click();
            }, 5000);
        });

    </script>
}