FloridoERPTX/Controllers/Item/ItemSpeckController.cs
using App.BLL.Item;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FloridoERPTX.Controllers.Item
{
    public class ItemSpeckController : Controller
    {
        // GET: ItemSpeck
        private readonly ItemSpeckBusiness _ItemSpeckBusiness;
        public ItemSpeckController()
        {
            _ItemSpeckBusiness = new ItemSpeckBusiness();
        }

        public ActionResult ActionPartSpeck(string PartNumber)
        {
            if (Session["User"] != null)
            {
                return Json(_ItemSpeckBusiness.ListItemSpeck(PartNumber), JsonRequestBehavior.AllowGet);
            }
            return Json("SF", JsonRequestBehavior.AllowGet);
        }
    }
}

FloridoERPTX/Controllers/Item/ItemsController.cs
using App.BLL;
using App.BLL.Configuration;
using App.BLL.CostCenter;
using App.BLL.EntryFree;
using App.BLL.Inventory;
using App.BLL.Item;
using App.BLL.PurchaseOrder;
using App.BLL.Rma;
using App.BLL.Sales;
using App.BLL.Site;
using App.BLL.Transfer;
using App.Common;
using App.Entities;
using App.Entities.ViewModels.DamagedsGoods;
using App.Entities.ViewModels.Item;
using DevExpress.XtraReports.UI;
using FloridoERPTX.Reports;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using System.Web.Mvc;
using App.Entities.ViewModels.Transfer;
using FloridoERPTX.Controllers.Transfer;

namespace FloridoERPTX.Controllers.Item
{
    public class ItemsController : Controller
    {
        private readonly ItemBusiness _ItemBusiness;
        private readonly ItemStockBusiness _ItemStockBusiness;
        private readonly SiteConfigBusiness _siteConfigBusiness;
        private readonly Common common;
        private readonly SendMail information;
        private readonly PurchaseOrderBusiness _purchaseOrderBusiness;
        private readonly UserMasterBusiness _userMasterBusiness;
        private readonly DamagedsGoodsBusiness _RmaHeadBusiness;
        private readonly InventoryReportBusiness _inventoryReportBusiness;
        private readonly SysRoleMasterBusiness _sysRoleMasterBusiness;
        private readonly SiteBusiness _siteBusiness;
        private readonly TransferHeaderBusiness _transferHeaderBusiness;
        private readonly SalesDetailBusiness _salesDetailBusiness;
        private readonly SalesBusiness _salesBusiness;
        private readonly EntryFreeHeadBusiness _entryFreeBusiness;
        private readonly CostCenterBusiness _costCenterBusiness;
        private readonly DamagedsGoodsItemBusiness _DamagedsGoodsItemBusiness;
        private readonly InventoryAdjustmentsBusiness _inventoryAdjustmentBusiness;

        public ItemsController()
        {
            _ItemBusiness = new ItemBusiness();
            _ItemStockBusiness = new ItemStockBusiness();
            _siteConfigBusiness = new SiteConfigBusiness();
            _purchaseOrderBusiness = new PurchaseOrderBusiness();
            _userMasterBusiness = new UserMasterBusiness();
            _RmaHeadBusiness = new DamagedsGoodsBusiness();
            _inventoryReportBusiness = new InventoryReportBusiness();
            _sysRoleMasterBusiness = new SysRoleMasterBusiness();
            _siteBusiness = new SiteBusiness();
            common = new Common();
            information = new SendMail();
            _transferHeaderBusiness = new TransferHeaderBusiness();
            _salesDetailBusiness = new SalesDetailBusiness();
            _salesBusiness = new SalesBusiness();
            _entryFreeBusiness = new EntryFreeHeadBusiness();
            _DamagedsGoodsItemBusiness = new DamagedsGoodsItemBusiness();
            _costCenterBusiness = new CostCenterBusiness();
            _inventoryAdjustmentBusiness = new InventoryAdjustmentsBusiness();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ActionListItem()
        {
            return Json(_ItemBusiness.GetAll(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionSearchItem(string Filter)
        {
            return new JsonResult() { Data = new { Json = _ItemBusiness.SerchItem(Filter) }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }
        public ActionResult ActionSearchItemNegativeDet(string Filter , string negative)
        {
            return new JsonResult() { Data = new { Json = _ItemBusiness.SerchItemNegativeDet(Filter,negative) }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }

        public ActionResult ActionSearchItemNegative(string Filter)
        {
            return new JsonResult() { Data = new { Json = _ItemBusiness.SerchItemNegative(Filter) }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }

        public ActionResult ActionSearchItemValidateNo(string Filter, string NoFilter)
        {
            return new JsonResult() { Data = new { Json = _ItemBusiness.SearchItemValidateNo(Filter, NoFilter) }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }

        public ActionResult ActionRemoveInventoryNegativa(int id_inventory_negative)
        {
            return new JsonResult() { Data = new { Json = _ItemStockBusiness.UpdateItemInventoryNegative(id_inventory_negative, Session["User"].ToString()), products = _inventoryAdjustmentBusiness.GetAllNegativeHeader() }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }

        public ActionResult ActionRemoveInventoryNegativaInfo(string part_number)
        {
            return new JsonResult() { Data = new { Json = _ItemStockBusiness.NegativeInventoryBalanceByPartNumber(part_number) }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }

        public ActionResult ActionAddItemInventoryNegative(string origin, string destination, decimal quantity, string reason)
        {
            return new JsonResult() { Data = new { Json = _ItemStockBusiness.AddItemInventoryNegative(origin, destination, quantity, reason, Session["User"].ToString()), products = _ItemStockBusiness.GetAllInvetoriesNegative() }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }

        public ActionResult ActionSearchItemBarcode(string Filter)
        {
            return new JsonResult() { Data = new { Json = _ItemBusiness.SerchItemBarcode(Filter) }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }
        public ActionResult ActionSearchItemBarcodePreInventory(string Filter)
        {
            return new JsonResult() { Data = new { Json = _ItemBusiness.SerchItemBarcodePreInventory(Filter) }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }

        public ActionResult ActionItemBarcodeComboPresentation(string Filter)
        {
            return new JsonResult() { Data = new { Json = _ItemBusiness.SearchItemBarcodeComboPresentation(Filter) }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }

        public ActionResult ActionSearchItemBarcodeSupplier(string Filter, int Supplier)
        {
            return new JsonResult() { Data = new { Json = _ItemBusiness.SearchItemBarcodeSupplier(Filter, Supplier) }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }
        public ActionResult ActionSearchItemBarcodeSupplierCurrency(string Filter, int Supplier , string Currency)
        {
            return new JsonResult() { Data = new { Json = _ItemBusiness.SearchItemBarcodeSupplierCurrency(Filter, Supplier,Currency) }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }

        public ActionResult ActionGetItemStockSelectStock(string PartNumber)
        {
            if (Session["User"] != null)
            {
                var Item = _ItemStockBusiness.GetItemStockSelectStock(PartNumber);

                if (Item != null)
                    return Json(new { Status = true, value = Item.Stock }, JsonRequestBehavior.AllowGet);

                return Json(new { Status = false, value = "" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Status = false, value = "SF" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionGetItemStock(string PartNumber)
        {
            if (Session["User"] != null)
            {
                var Item = _ItemStockBusiness.GetItemStock(PartNumber);

                if (Item != null)
                    return Json(new { Status = true, Item = Item }, JsonRequestBehavior.AllowGet);

                return Json(new { Status = false }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Status = false }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionGetInventoryAdjustmentRequestsByDate(DateTime beginDate, DateTime endDate)
        {
            return Json(new { success = true, Json = _ItemStockBusiness.GetInventoryAdjustmentRequestsByDate(beginDate, endDate) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionGetInventoryAdjustmentRequests()
        {
            return Json(new { success = true, Json = _ItemStockBusiness.GetInventoryAdjustmentRequests() }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionGetInfoProducts(string part_numbers, int deparment, int family)
        {
            return Json(new { success = true, Json = _ItemBusiness.NewGetAllItems(part_numbers, deparment, family) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionSetItemStock(List<ItemModel> model)
        {
            if (Session["User"] != null)
            {
                string document;
                model = _ItemStockBusiness.SetItemStock(model, Session["User"].ToString(), out document);
                if (model != null)
                {
                    string Gerente = _sysRoleMasterBusiness.GetEmailsByRol(ConfigurationManager.AppSettings["Gerente"].ToString());
                    var infoIventoryCC = _ItemBusiness.GetInformationInventoryCC(document);
                    var infoSite = _siteBusiness.GetInfoSite();
                    Task task = new Task(() =>
                    {
                        SolicitudAjusteInventario reporte = new SolicitudAjusteInventario();
                        reporte.DataSource = reporte.printTable(model, infoIventoryCC, infoSite);
                        Stream stream = new MemoryStream();

FloridoERPTX/Views/Items/ITEM001.cshtml
@{ ViewBag.Title = "ITEM002"; }

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("SALE000","Sales")">Ventas</a></li>
                    <li><a href="@Url.Action("SALE004","Sales")">Movimientos</a></li>
                    <li class="active">
                        <span>Consulta Rápida</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Consulta Rápida
            </h2>
            <small>Consulta Rápida de Artículos</small>
        </div>
    </div>
</div>
<div class="content animate-panel">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel hblue">
                <div class="panel-body">
                    <div id="divItems">
                        <div class="row">
                            <div class="col-lg-3" hidden>
                                <label title="Producto" data-toggle="tooltip" data-placement="right">Producto</label>
                                <input class="form-control" id="ItemsDrop" name="ItemsDrop" />
                            </div>
                            <div class="col-lg-4">
                                <label title="Producto a Buscar" data-toggle="tooltip" data-placement="right">Artículo a buscar</label>
                                <input class="form-control" id="ItemsLike" />
                            </div>
                            <div class="form-group col-lg-2">
                                <br />
                                <button class="btn btn-success" id="btnSearchItems" onclick="SearchItems()"><i class="fa fa-search"></i> Buscar</button>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div id="divTable" class="animate-panel" data-effect="zoomIn">
                        <div class="row table-responsive">
                            <table id="TableProducts" class="table table-striped table-bordered table-hover" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Código</th>
                                        <th>Descripción</th>
                                        <th>Existencias</th>
                                        <th>Bloqueo</th>
                                        <th>Mat. Prima</th>
                                        <th>Disponible</th>                                       
                                        <th>Precio</th>
                                        <th>Precio c/IVA</th>
                                        <th>Presentaciones</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">

        const formatmoney = money => decimal => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", currencyDisplay: "symbol", maximumFractionDigits: decimal }).format(money);
        var input = document.getElementById("ItemsLike");
        input.addEventListener("keyup", function (event) {
            if (event.keyCode === 13) {
                event.preventDefault();
                document.getElementById("btnSearchItems").click();
            }
        });

        $("#ItemsDrop").select2({
            minimumInputLength: 3,
            allowClear: true,
            placeholder: "Seleccione una producto",
            initSelection: function (element, callback) {
                callback({ id: "", text: "Seleccione una opcion" });
            },
            ajax: {
                url: "/Items/ActionSearchItemBarcode/",
                dataType: 'json',
                type: "GET",
                quietMillis: 50,
                data: function (Filter) {
                    return {
                        Filter: Filter
                    };
                },
                results: function (data) {
                    return {
                        results: $.map(data.Json, function (item) {
                            return {
                                text: item.Description,
                                id: item.PathNumber
                            }
                        }),
                    };
                }
            }
        });

        $(document).ready(function () {
            window.setTimeout(function () { $("#fa").click(); }, 1000);
        });

        var table = $('#TableProducts').DataTable({
            oLanguage:
            {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": { "sFirst": "Primero", "sLast": "Último", "sNext": "Siguiente", "sPrevious": "Anterior" },
                "oAria": { "sSortAscending": ": Activar para ordenar la columna de manera ascendente", "sSortDescending": ": Activar para ordenar la columna de manera descendente" }
            },
            dom: "<'row'<'col-sm-4'l><'col-sm-4 text-left'B><'col-sm-4'f>t<'col-sm-6'i><'col-sm-6'p>>",
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            buttons: [],
            columns:
                [
                    { data: 'PartNumber' },
                    { data: 'Description' },
                    { data: 'Total_Stock' },
                    { data: 'Blocked' },
                    { data: 'Wip' },
                    { data: 'Stock' },
                    { data: 'BasePrice' },
                    { data: 'TaxPrice' },
                    { data: 'Presentations' }
                ],
            columnDefs:
                [
                    {
                        targets: [0],
                        width: "1%"
                    },
                    {
                        targets: [1],
                        width: "1%"
                    },
                    {
                        targets: [2,3,4,5],
                        render: function (data, type, full, meta) {
                            return `${data.toFixed(2)}`;
                        },
                        width: "1%"
                    },
                    {
                        targets: [6,7],
                        render: function (data, type, full, meta) {
                            return `${formatmoney(data)(2)}`;
                        },
                        width: "1%"
                    },
                    {

                        targets: [8],
                        width: "1%",
                        render: function (data, type, full, meta) {
                            var html = "<ul>";
                            data.forEach(e => html += "<li>" + e.Description + " $" + e.TaxPrice + "</li>");
                            html += "</ul>";
                            return html;
                        }
                    }
                ]
        });

        //Funcion para obtener inventario activo
        function SearchItems() {
            var itemLike = $("#ItemsLike").val();
            if (itemLike.trim().length < 3) {
                toastr.warning("Por favor , introduzca por lo menos 3 caracteres");
                return;
            }
            StartLoading();
            $.ajax({
                url: "/Items/ActionSearchItems",
                data: {"item":itemLike},
                type: "POST",
                success: function (json) {
                    if (json.success) {
                        if (json.data.length > 0) {
                            table.clear().draw();
                            table.rows.add(json.data)
                            table.columns.adjust().draw();
                            EndLoading();
                            $('#divTable').animatePanel();
                        } else {
                            toastr.warning("No se encontraron productos")
                            EndLoading();
                        }

                    } else {
                        if (json.data == "SF") {
                            EndLoading();
                            SessionFalse("Se terminó tu sesión");
                        }
                        EndLoading();
                        toastr.error("DESCONOCIDO, CONTACTA A SISTEMAS.");
                    }
                },
                error: function () {
                    EndLoading();
                    toastr.error("DESCONOCIDO, CONTACTA A SISTEMAS.");
                }
            });
        }
    </script>
}

FloridoERPTX/Views/Items/ITEM002.cshtml
@model App.Entities.ViewModels.Item.ItemQuickCheckIndex
@{ ViewBag.Title = "ITEM001"; }

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("SALE000","Sales")">Ventas</a></li>
                    <li><a href="@Url.Action("SALE004","Sales")">Movimientos</a></li>
                    <li class="active">
                        <span>Cotizaciones/Pedidos</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Consulta Rápida
            </h2>
            <small>Consultar Artículos</small><br />
        </div>
    </div>
</div>

@if (Model.IsFromMenu)
{
    <div class="content animated-panel" id="SelectClient">
        <div class="hpanel hblue">
            <div class="panel-body">
                <form id="formQuoteClient" action="@Url.Action("ITEM001", "Items")" method="post">
                    @Html.HiddenFor(model => model.IsFromMenu)
                    <div class="form-group col-md-12" id="SearchClient">
                        @Html.LabelFor(model => model.ItemSearch, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10 input-group m-b">
                            @Html.EditorFor(model => model.ItemSearch, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                    <div class="col-lg-12" style="">
                        <div class="form-group col-lg-12">
                            <div class="text-right">
                                <button type="submit" class="btn btn-success" id="SearchItem">Continuar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
}
@if (!Model.IsFromMenu && Model.ItemList.Count > 0)
{
    <div class="content animated-panel">
        <div class="hpanel hblue">
            <div class="panel-body">
                <div class="table-responsive m-t">
                    <table id="ItemTable" class="table table-striped table-bordered table-hover" style="width:100%">
                        <thead>
                            <tr>
                                <th>Número de Artículo</th>
                                <th>Descripción</th>
                                <th>Existencia</th>
                                <th>Precio</th>
                                <th>Precio c/IVA</th>
                                <th>Presentación</th>
                                <th>Presentación</th>
                                <th>Presentación</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ItemList)
                            {
                                <tr>
                                    <td>@item.PartNumber</td>
                                    <td>@item.Description</td>
                                    <td>@item.Stock</td>
                                    <td>@item.BasePrice.ToString("C")</td>
                                    <td>@item.TaxPrice.ToString("C")</td>
                                    @{var p = item.Presentations;}
                                    @for (var i = 0; i < 3; i++)
                                    {
                                        <td>
                                            @if (p.Count > i)
                                            {
                                                <span style="white-space: nowrap; font-size: 0.85em;"> @p[i].Description </span><br />@p[i].TaxPrice.ToString("C")
                                            }
                                        </td>
                                    }
                                </tr>
                                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
                                        }
                                        else if (!Model.IsFromMenu)
                                        {
                                            <div class="content animated-panel" id="report-section">
                                                <div class="hpanel hblue">
                                                    <div class="panel-body">
                                                        <div class="row">
                                                            <h4 style="text-align:center;color:red;">No hay información con esos parámetros</h4>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        }

@section Scripts { @Scripts.Render("~/bundles/ITEM001/js") }