FloridoERPTX/Controllers/TransactionsCustomers/TransactionsCustomersController.cs
using App.BLL.Currency;
using App.BLL.Payments;
using App.BLL.TransactionsCustomers;
using App.Entities;
using App.Entities.ViewModels.Common;
using App.Entities.ViewModels.Payments;
using App.Entities.ViewModels.TransactionsCustomers;
using DevExpress.XtraReports.UI;
using FloridoERP.Report;
using FloridoERPTX.CommonMethods;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FloridoERPTX.TransactionsCustomers
{
    public class TransactionsCustomersController : Controller
    {
        private CurrencyBusiness _CurrencyBusiness;
        private TransactionsCustomersBusiness _TransactionsCustomersBusiness;
        private PaymentsBusiness _PaymentsBusiness;
        private CustomerLookup _CustomerLookup;

        public TransactionsCustomersController()
        {
            _CurrencyBusiness = new CurrencyBusiness();
            _TransactionsCustomersBusiness = new TransactionsCustomersBusiness();
            _PaymentsBusiness = new PaymentsBusiness();
            _CustomerLookup = new CustomerLookup();
        }

        public ActionResult TRAC001()
        {
            var Model = new TransactionsCustomersReport();
            ViewBag.Currency = new SelectList(_CurrencyBusiness.CurrencyList(), "cur_code", "cur_name");            
            ViewBag.CustomerCode = _CustomerLookup.FillLookupCustomer(CustomersLookup.ByTransactions);
            return View(Model);
        }

        [HttpPost]
        public ActionResult TRAC001(TransactionsCustomersReport Model)
        {
            Model.ReportList = _TransactionsCustomersBusiness.GetReportData(Model);
            Model.IsFromMenu = false;
            ViewBag.Currency = new SelectList(_CurrencyBusiness.CurrencyList(), "cur_code", "cur_name");            
            ViewBag.CustomerCode = _CustomerLookup.FillLookupCustomer(CustomersLookup.ByTransactions);
            return View(Model);
        }        

        [HttpPost]
        public ActionResult ActionGetReport(TransactionsCustomersReport Model)
        {
            var Report = new ChargePaymentReport();
            (Report.Bands["DetailReport"] as DetailReportBand).DataSource = Report.printTable(Model);
            (Report.Bands["DetailReport"] as DetailReportBand).DataMember = "xrTableRowFormat";
            return PartialView("~/Views/ReportsViews/ChargePaymentReport.cshtml", Report);            
        }

        //pagos cancelados
        public ActionResult TRAC002()
        {
            ViewBag.CustomerCode = _CustomerLookup.FillLookupCustomer(CustomersLookup.ByCancelledPayments);            
            return View();
        }

        [HttpGet] //Get payments per client selected.
        public ActionResult ActionGetPaymentByCustomer(string CustomerCode)
        {
            var Payments = _PaymentsBusiness.PaymentsCancelledByCustomer(CustomerCode);
            return Json(new { success = true, Json = Payments, responseText = "Pagos de Clientes" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ActionPaymentsCacelledReport(TransactionsCustomersReport Model)
        {
            var Report = new ChargePaymentReport();
            (Report.Bands["DetailReport"] as DetailReportBand).DataSource = Report.printTable(Model);
            (Report.Bands["DetailReport"] as DetailReportBand).DataMember = "xrTableRowFormat";
            return PartialView("~/Views/ReportsViews/ChargePaymentReport.cshtml", Report);
        }
    }
}

FloridoERPTX/Views/TransactionsCustomers/TRAC001.cshtml
@model App.Entities.ViewModels.TransactionsCustomers.TransactionsCustomersReport

@{
    ViewBag.Title = "TRAC001";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Breadcrumb*@
<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("CTMS000","Customers")">Clientes</a></li>
                    <li><a href="@Url.Action("CTMS001","Customers")">Reportes</a></li>
                    <li class="active">
                        <span>Cargos y Abonos</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Cargos y Abonos
            </h2>
            <small>Reporte</small><br />
        </div>
    </div>
</div>

<div class="content animated-panel">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel hblue">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <form id="formReport" action="@Url.Action("TRAC001","TransactionsCustomers")" method="post">
                        <div class="row">
                            <div class="form-group col-md-3">
                                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label" })
                                <div class="col-md-10 input-group m-b">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                </div>
                            </div>
                            <div class="form-group col-md-3">
                                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label" })
                                <div class="col-md-10 input-group m-b">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })

                                </div>
                            </div>
                            <div class="form-group col-md-3">
                                @Html.LabelFor(model => model.Currency, htmlAttributes: new { @class = "control-label" })
                                <div class="col-md-10 input-group m-b">
                                    @Html.DropDownListFor(model => model.Currency, null, htmlAttributes: new { @class = "form-control select2" })
                                </div>
                            </div>              
                            <div class="text-left col-md-3">
                                <label class="control-label">&nbsp;</label>
                                <div class="text-left">
                                    <button type="button" class="btn btn-success" id="SearchReport">Continuar</button>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12" id="SearchClient">
                                @Html.LabelFor(model => model.CustomerCode, htmlAttributes: new { @class = "control-label" })
                                <div class="col-md-10 input-group m-b">
                                    @Html.DropDownListFor(model => model.CustomerCode, null, "-- Selecciona Cliente--", htmlAttributes: new { @class = "form-control select2" })
                                    <label>(Buscar cliente por RFC, Nombre o Número)</label>
                                </div>
                            </div>                            
                        </div>
                    </form>
                </div>
                
                @if (!Model.IsFromMenu && Model.ReportList.Count > 0)
                {
                    <div class="content animated-panel" id="TableSection">
                        <div class="hpanel">
                            <div class="panel-body">
                                <div class="text-center">
                                    <button type="button" class="btn btn-success" id="ReportButton">Reporte General</button>
                                </div>
                                <div class="table-responsive m-t">
                                    <table id="reportTable" class="table table-striped table-bordered table-hover" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>No. Cliente</th>
                                                <th>Cliente</th>
                                                <th>Fecha</th>
                                                <th>Cargo</th>
                                                <th>Abono</th>
                                                <th>Referencia</th>
                                                <th>CargoCantidad</th>
                                                <th>AbonoCantidad</th>
                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr style="font-weight:bold;">
                                                <td colspan="3" class="text-right">Total</td>
                                                <td id="TotalCharge">$ @Model.ReportList.Sum(c=>c.Charge).ToString("0.00")</td>
                                                <td id="TotalPayment" colspan="3" class="text-left">$@Model.ReportList.Sum(c => c.Payment).ToString("0.00")</td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                else if (!Model.IsFromMenu)
                {
                    <div class="content animated-panel" id="report-section">
                        <div class="hpanel hblue">
                            <div class="panel-body">
                                <div class="row">
                                    <h4 style="text-align:center;color:red;">No hay información con esos parámetros</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="modal fade hmodal-info" id="ModalReport" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="color-line"></div>
            <div class="modal-header">
                <h4 id="ModalTitle" class="modal-title">Reporte de Cargos y Abonos</h4>
                <small id="ModalDescription" class="font-bold"></small>
            </div>
            <div class="modal-body">
                <div class="row">
                    <iframe id="iframe" style="width:100%" height="350" frameborder="0"></iframe>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
@Scripts.Render("~/bundles/datepicker/js")
@Scripts.Render("~/bundles/datatables/js")
@Scripts.Render("~/bundles/datatablesBootstrap/js")
@Scripts.Render("~/bundles/datatablesPlugins/js")
<script src="~/Scripts/validations.js"></script>
    <script type="text/javascript">
        $(function () {

            var reportList = @Html.Raw(Json.Encode(Model.ReportList));
            reportTable.clear();
            reportTable.rows.add(jQuery(reportList));
            reportTable.columns.adjust().draw();

            $("#StartDate").datepicker({
                autoclose: true,
                format: 'dd/mm/yyyy',
                language: 'es',
                endDate: new Date()
            });

            $("#EndDate").datepicker({
                autoclose: true,
                todayHighlight: true,
                format: 'dd/mm/yyyy',
                language: 'es',
                endDate: new Date()
            });

            $(".datepicker").attr('readonly', 'readonly').css('background-color', '#fff');
        });

        $("#SearchReport").click(function () {
            var startDate = $("#StartDate").val();
            var endDate = $("#EndDate").val();

            if(ValidateDates(startDate,endDate))
            {
                StartLoading();
                $("#formReport").submit();
            }
        });

        var reportTable = $('#reportTable').DataTable({
            oLanguage: {
                "sProcessing": "Procesando...", "sLengthMenu": "Mostrar _MENU_ registros", "sZeroRecords": "No se encontraron resultados", "sEmptyTable": "Ningún dato disponible en esta tabla", "sInfo": "Mostrando registros", "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros", "sInfoFiltered": "(filtrado de un total de _MAX_ registros)", "sInfoPostFix": "", "sSearch": "Buscar:", "sUrl": "", "sInfoThousands": ",", "sLoadingRecords": "Cargando...", "oPaginate": { "sFirst": "Primero", "sLast": "Último", "sNext": "Siguiente", "sPrevious": "Anterior" }, "oAria": { "sSortAscending": ": Activar para ordenar la columna de manera ascendente", "sSortDescending": ": Activar para ordenar la columna de manera descendente" }
            },
            dom: "<'row'<'col-sm-4'l><'col-sm-4 text-left'B><'col-sm-4'f>t<'col-sm-6'i><'col-sm-6'p>>",
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            buttons: [],
            columns: [
                { data: 'ClientNumber' },
                { data: 'ClientName' },
                { data: 'Date' },
                { data: 'ChargeText' },
                { data: 'PaymentText' },
                { data: 'Reference' },
                { data: 'Charge' },
                { data: 'Payment' }
            ],

            columnDefs: [
                {
                    className: 'text-center'
                },
                {
                    targets: [6, 7],
                    visible: false
                },
            ]
        });

        $("#ReportButton").click(function() {
            var model = @Html.Raw(Json.Encode(Model));
            StartLoading();
            $.post({
                url: '@Url.Action("ActionGetReport", "TransactionsCustomers")',
                Type: 'POST',
                data: { "Model": model },
                success: function (data) {
                    EndLoading();
                    document.getElementById("iframe").srcdoc = data;
                    $("#ModalDescription").html('Reporte de Cargos y Abonos');
                    $('#ModalReport').modal('show');                   
                },
                error: function () {                    
                    toastr.error('Alerta - Error inesperado  contactar a sistemas.');
                }
            });
        });
    </script>
}

FloridoERPTX/Views/TransactionsCustomers/TRAC002.cshtml
@model App.Entities.ViewModels.Payments.PaymentIndex

@{
    ViewBag.Title = "TRAC002";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    td.details-control:before {
        display: inline-block;
        font: normal normal normal 14px/1 FontAwesome;
        font-size: inherit;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
        content: "\f101";
        cursor: pointer;
    }

    tr.details td.details-control:before {
        display: inline-block;
        font: normal normal normal 14px/1 FontAwesome;
        font-size: inherit;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
        content: "\f103";
        cursor: pointer;
    }
</style>

@*Breadcrumb*@
<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("CTMS000","Customers")">Clientes</a></li>
                    <li><a href="@Url.Action("CTMS006","Customers")">Caja</a></li>
                    <li class="active">
                        <span>Pagos Cancelados</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Pagos Cancelados
            </h2>
            <small>Pagos Cancelados por cliente</small><br />
        </div>
    </div>
</div>

<div class="content animated-panel">
    <div class="hpanel hblue">
        <div class="panel-body">
            <div class="form-group col-md-12" id="SearchClient">
                @Html.LabelFor(model => model.CustomerCode, htmlAttributes: new { @class = "control-label" })
                <div class="col-md-10 input-group m-b">
                    @Html.DropDownListFor(model => model.CustomerCode, null, "-- Selecciona Cliente--", htmlAttributes: new { @class = "form-control select2" })
                    <label>(Buscar cliente por RFC, Nombre o Número)</label>
                </div>
            </div>
            <div class="form-group col-md-10" id="TableSection" style="display:inline-block;">
                <div class="hpanel">
                    <div class="panel-body">
                        <table id="PaymentsTable" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th># Recibo</th>
                                    <th>Fecha de Recibo</th>
                                    <th>Método de Pago</th>
                                    <th>Número de Operación</th>
                                    <th>Importe</th>
                                    <th>Fecha de Pago</th>
                                    <th>Fecha de Cancelación</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        $(function () {
            $("#TableSection").hide();
        });

        $("#CustomerCode").on('change', function () {
            var clientValue = $("#CustomerCode").val();
            if (clientValue) {
                $.ajax({
                    url: '@Url.Action("ActionGetPaymentByCustomer", "TransactionsCustomers")',
                    Type: 'GET',
                    data: { CustomerCode: clientValue },
                    dataType: 'json',
                    success: function (data) {
                        $("#TableSection").show();
                        table.clear();
                        table.rows.add(data.Json);
                        table.columns.adjust().draw();
                    }
                });
            }
            $("#TableSection").hide();
        });

        var table = $('#PaymentsTable').DataTable({
            oLanguage: {
                "sProcessing": "Procesando...", "sLengthMenu": "Mostrar _MENU_ registros", "sZeroRecords": "No se encontraron resultados", "sEmptyTable": "Ningún dato disponible en esta tabla", "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros", "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros", "sInfoFiltered": "(filtrado de un total de _MAX_ registros)", "sInfoPostFix": "", "sSearch": "Buscar:", "sUrl": "", "sInfoThousands": ",", "sLoadingRecords": "Cargando...", "oPaginate": { "sFirst": "Primero", "sLast": "Último", "sNext": "Siguiente", "sPrevious": "Anterior" }, "oAria": { "sSortAscending": ": Activar para ordenar la columna de manera ascendente", "sSortDescending": ": Activar para ordenar la columna de manera descendente" }
            },
            dom: "<'row'<'col-sm-4'l><'col-sm-4 text-left'B><'col-sm-4'f>t<'col-sm-6'i><'col-sm-6'p>>",
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            buttons: [

            ],
            columns: [
                {
                    "class": "details-control",
                    "orderable": false,
                    "data": null,
                    "defaultContent": "",
                },
                { data: 'PMId' },
                { data: 'Receipt' },
                { data: 'ReceiptDate' },
                { data: 'PaymentMethod' },
                { data: 'OperationNumber' },
                { data: 'Amount' },
                { data: 'PaymentDate' },
                { data: 'PaymentDateCancel' },
            ],

            columnDefs: [
                {
                    type: 'numeric-comma',
                    render: function (data, type, row) {
                        return '$' + data.toFixed(2);
                    },
                    targets: [6]
                },
                {
                    className: 'text-center'
                },
                { orderable: false, targets: [0, 8] },
                { visible: false, targets: [1] }]
        });

        var detailRows = [];

        $('#TableSection tbody').on('click', 'tr td.details-control', function () {
            var tr = $(this).closest('tr');
            var row = table.row(tr);

            if (row.child.isShown()) {
                row.child.hide();
                tr.removeClass('details');
            }
            else {
                if (table.row('.details').length) {
                    $('.details-control', table.row('.details').node()).click();
                }
                row.child(dataPayments(row.data())).show();
                tr.addClass('details');
            }
        });

        table.on('draw', function () {
            $.each(detailRows, function (i, id) {
                $('#' + id + ' td.details-control').trigger('click');
            });
        });

        //Get Invoice paid per payment(receipt number)
        function dataPayments(row) {
            var detailItems = "";
            var tabledetail = $('<div/>').addClass('loading').text('Cargando Datos...');
            $.ajax({
                url: "@(Url.Action("ActionGetInvoicesPaidByPayment", "Payments"))",
                data: { "PaymentId": row.PMId },
                type: "GET",
                success: function (data) {
                    $.each(data.Json, function (index, value) {
                        detailItems += "<tr><td>" + value.Invoice + "</td><td class='text-right'>" + "$" + value.PaymentInvoice.toFixed(2) + "</td><td class='text-right'>" + "$" + value.Balance.toFixed(2) + "</td></tr>"
                    });
                    tabledetail.html('<table id="InvoicePaidDetails" class="table table-striped table-bordered table-hover" style="width:100%">' +
                    '<thead><tr><th>No. Factura</th><th>Pago/Abono</th><th>Saldo Factura</th></tr></thead><tbody>' + detailItems + '</tbody></table>').removeClass('loading');
                    reloadStyleTable();
                }
            });
            return tabledetail
        }

        function reloadStyleTable() {
            $('#InvoicePaidDetails').DataTable({
                oLanguage: {
                    "sProcessing": "Procesando...", "sLengthMenu": "Mostrar _MENU_ registros", "sZeroRecords": "No se encontraron resultados", "sEmptyTable": "Ningún dato disponible en esta tabla", "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros", "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros", "sInfoFiltered": "(filtrado de un total de _MAX_ registros)", "sInfoPostFix": "", "sSearch": "Buscar:", "sUrl": "", "sInfoThousands": ",", "sLoadingRecords": "Cargando...", "oPaginate": { "sFirst": "Primero", "sLast": "Último", "sNext": "Siguiente", "sPrevious": "Anterior" }, "oAria": { "sSortAscending": ": Activar para ordenar la columna de manera ascendente", "sSortDescending": ": Activar para ordenar la columna de manera descendente" }
                },
            });
        }

      
    </script>
}